# Generated by Django 5.0.2 on 2024-08-18 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='meter_number',
            field=models.IntegerField(),
        ),
    ]
