# Generated by Django 5.0.2 on 2024-08-18 06:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_alter_customers_meter_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='customers',
            name='request_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
